server:
  port: 8087
spring:
  application:
    name: slack-service
  datasource:
    url: jdbc:postgresql://database:5432/spartahubflow
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

# application.yml


slack:
  token: ${SLACK_TOKEN}


management:
  zipkin:
    tracing:
      endpoint: "http://host.docker.internal:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}