spring:
  application:
    name: slack-service  # ??? ?? ??
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # Eureka ?? URL
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: slack-service-group
        auto-offset-reset: earliest
      properties:
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer

slack:
  token: YOUR_SLACK_BOT_TOKEN
  channel: YOUR_SLACK_CHANNEL_ID
server:
  port: 8091 # ??? ??

