spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/spartahubflow
    username: postgres
    password: 1234

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
        show_sql: true
        use_sql_comments: true

#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0


server:
  port: 4
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/