spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spartahubflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    
management:
  zipkin:
    tracing:
      endpoint: "http://host.docker.internal:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: DEBUG
